class GathererScraper
  require 'open-uri'
  require 'uri'

  ROOT_URL = "http://gatherer.wizards.com/Pages"

  # GathererScraper.reset_and_restart
  def self.reset_and_restart
    #Card.all.destroy_all
    #ExtensionSet.all.destroy_all
    self.process
  end

  # javascript
  # elements = document.querySelectorAll('table.compact tr.cardItem td.name a');
  # results = [];
  # for(n = 0; n < elements.length; n++) {
  #   results.push(elements[n].getAttribute('href'));
  # }
  # results;

  def self.process
    EXTENSION_NAME.each do |set_name|
      page        = -1
      card_links  = []
      loop do
        page    += 1
        url     = "http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[#{set_name.gsub(' ', '+')}]&page=#{page}&output=compact"
        puts "going to #{set_name} (#{page}) : #{url}"
        client  = HTTPClient.new(default_header: { "Accept-Language" => "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7" }).get(url)
        doc     = Nokogiri::HTML(client.body)

        links = doc.css('table.compact tr.cardItem td.name a').collect do |card_link|
          card_link.attribute('href').value.sub('..', ROOT_URL)
        end
        puts "#{links.count} cards found !"
        if page == 0 && links.count == 0
          puts "no result found for #{set_name}"
          break
        end
        break if card_links.include?(links.last)
        puts "continuing..."
        card_links += links
      end
      set_id = self.find_or_create(set_name)
      self.import_cards(set_id, card_links)
    end
  end

  def self.import_gatherer_card_url
    GathererCardUrl.all.find_each do |gatherer_url|
      ImportCard.new(gatherer_url.url, gatherer_url.extension_set_id)
    end
  end

  def self.find_or_create(set_name)
    if (set = ExtensionSet.where(name: set_name).first)
      puts "retrieving #{set_name}"
      set.id
    else
      ExtensionSet.create(name: set_name).id
    end
  end

  def self.import_cards(set_id, card_links)
    puts "#{set_id} : #{card_links.uniq.count}"
    card_links.each do |card_url|
      puts card_url
      ImportCard.new(card_url, set_id)
    end
  end

  def self.fail_sets
    @fail_sets ||= EXTENSION_NAME.collect do |set_name|
      ExtensionSet.where(name: set_name).first.cards.count.positive? ? nil : set_name
    end.compact
  end

  def self.import_failed_urls
    FAILED_URLS_1.each do |card_url|
      # puts card_url
      ImportCard.new(card_url, nil)
    end
  end

  EXTENSION_NAME = [
    "Aether Revolt",
    "Alara Reborn",
    "Alliances",
    "Amonkhet",
    "Antiquities",
    "Apocalypse",
    "Arabian Nights",
    "Archenemy",
    "Archenemy: Nicol Bolas",
    "Avacyn Restored",
    "Battle for Zendikar",
    "Battle Royale Box Set",
    "Battlebond",
    "Beatdown Box Set",
    "Betrayers of Kamigawa",
    "Born of the Gods",
    "Champions of Kamigawa",
    "Chronicles",
    "Classic Sixth Edition",
    "Coldsnap",
    "Commander 2013 Edition",
    "Commander 2014",
    "Commander 2015",
    "Commander 2016",
    "Commander 2017",
    "Commander 2018",
    "Commander Anthology",
    "Commander Anthology 2018",
    "Commander's Arsenal",
    "Conflux",
    "Conspiracy: Take the Crown",
    "Core Set 2019",
    "Dark Ascension",
    "Darksteel",
    "Dissension",
    "Dominaria",
    "Dragon's Maze",
    "Dragons of Tarkir",
    "Duel Decks Anthology, Divine vs. Demonic",
    "Duel Decks Anthology, Elves vs. Goblins",
    "Duel Decks Anthology, Garruk vs. Liliana",
    "Duel Decks Anthology, Jace vs. Chandra",
    "Duel Decks: Ajani vs. Nicol Bolas",
    "Duel Decks: Blessed vs. Cursed",
    "Duel Decks: Divine vs. Demonic",
    "Duel Decks: Elspeth vs. Kiora",
    "Duel Decks: Elspeth vs. Tezzeret",
    "Duel Decks: Elves vs. Goblins",
    "Duel Decks: Elves vs. Inventors",
    "Duel Decks: Garruk vs. Liliana",
    "Duel Decks: Heroes vs. Monsters",
    "Duel Decks: Izzet vs. Golgari",
    "Duel Decks: Jace vs. Chandra",
    "Duel Decks: Jace vs. Vraska",
    "Duel Decks: Knights vs. Dragons",
    "Duel Decks: Merfolk vs. Goblins",
    "Duel Decks: Mind vs. Might",
    "Duel Decks: Nissa vs. Ob Nixilis",
    "Duel Decks: Phyrexia vs. the Coalition",
    "Duel Decks: Sorin vs. Tibalt",
    "Duel Decks: Speed vs. Cunning",
    "Duel Decks: Venser vs. Koth",
    "Duel Decks: Zendikar vs. Eldrazi",
    "Eighth Edition",
    "Eldritch Moon",
    "Eternal Masters",
    "Eventide",
    "Exodus",
    "Explorers of Ixalan",
    "Fallen Empires",
    "Fate Reforged",
    "Fifth Dawn",
    "Fifth Edition",
    "Fourth Edition",
    "From the Vault: Angels",
    "From the Vault: Annihilation (2014)",
    "From the Vault: Dragons",
    "From the Vault: Exiled",
    "From the Vault: Legends",
    "From the Vault: Lore",
    "From the Vault: Realms",
    "From the Vault: Relics",
    "From the Vault: Transform",
    "From the Vault: Twenty",
    "Future Sight",
    "Gatecrash",
    "Global Series: Jiang Yanggu and Mu Yanling",
    "Guild Kit: Boros",
    "Guild Kit: Dimir",
    "Guild Kit: Golgari",
    "Guild Kit: Izzet",
    "Guild Kit: Selesnya",
    "Guildpact",
    "Guilds of Ravnica",
    "Homelands",
    "Hour of Devastation",
    "Ice Age",
    "Iconic Masters",
    "Innistrad",
    "Invasion",
    "Ixalan",
    "Journey into Nyx",
    "Judgment",
    "Kaladesh",
    "Khans of Tarkir",
    "Legends",
    "Legions",
    "Limited Edition Alpha",
    "Limited Edition Beta",
    "Lorwyn",
    "Magic 2010",
    "Magic 2011",
    "Magic 2012",
    "Magic 2013",
    "Magic 2014 Core Set",
    "Magic 2015 Core Set",
    "Magic Origins",
    "Magic: The Gathering-Commander",
    "Magic: The Gathering—Conspiracy",
    "Masterpiece Series: Amonkhet Invocations",
    "Masterpiece Series: Kaladesh Inventions",
    "Masters 25",
    "Masters Edition",
    "Masters Edition II",
    "Masters Edition III",
    "Masters Edition IV",
    "Mercadian Masques",
    "Mirage",
    "Mirrodin",
    "Mirrodin Besieged",
    "Modern Event Deck 2014",
    "Modern Masters",
    "Modern Masters 2015 Edition",
    "Modern Masters 2017 Edition",
    "Morningtide",
    "Nemesis",
    "New Phyrexia",
    "Ninth Edition",
    "Oath of the Gatewatch",
    "Odyssey",
    "Onslaught",
    "Planar Chaos",
    "Planechase",
    "Planechase 2012 Edition",
    "Planechase Anthology",
    "Planeshift",
    "Portal",
    "Portal Second Age",
    "Portal Three Kingdoms",
    "Premium Deck Series: Fire and Lightning",
    "Premium Deck Series: Graveborn",
    "Premium Deck Series: Slivers",
    "Promo set for Gatherer",
    "Prophecy",
    "Ravnica: City of Guilds",
    "Return to Ravnica",
    "Revised Edition",
    "Rise of the Eldrazi",
    "Rivals of Ixalan",
    "Saviors of Kamigawa",
    "Scars of Mirrodin",
    "Scourge",
    "Seventh Edition",
    "Shadowmoor",
    "Shadows over Innistrad",
    "Shards of Alara",
    "Signature Spellbook: Jace",
    "Starter 1999",
    "Starter 2000",
    "Stronghold",
    "Tempest",
    "Tempest Remastered",
    "Tenth Edition",
    "The Dark",
    "Theros",
    "Time Spiral",
    "Time Spiral \"Timeshifted\"",
    "Torment",
    "Ugin's Fate promos",
    "Unglued",
    "Unhinged",
    "Unlimited Edition",
    "Unstable",
    "Urza's Destiny",
    "Urza's Legacy",
    "Urza's Saga",
    "Vanguard",
    "Vintage Masters",
    "Visions",
    "Weatherlight",
    "Welcome Deck 2016",
    "Welcome Deck 2017",
    "Worldwake",
    "Zendikar",
    "Zendikar Expeditions",
  ]

  not_created_ids = [220492, 221312, 220481, 220494, 220550] # TODO : import this cards

  FAILED_URLS_1 = [
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5716",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8437",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5551",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5636",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9713",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5722",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5865",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5867",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5603",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5714",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5781",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10420",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5572",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5733",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5764",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5736",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5686",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5862",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5769",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5596",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5711",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9856",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5735",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5727",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5605",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5617",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5623",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5747",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5612",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5737",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5597",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5564",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5848",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5633",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9890",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5577",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8886",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5567",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5858",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5620",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9852",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5637",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10659",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5762",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9678",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8858",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5552",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8868",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5724",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8890",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5692",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5718",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10426",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9702",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5768",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8815",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5613",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5853",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5665",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5546",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5555",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5668",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5742",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=7817",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5852",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5626",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5622",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5588",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10656",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10658",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10427",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5634",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5672",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8446",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5630",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5854",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10695",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5723",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8870",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5719",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5805",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5734",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5557",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5860",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9700",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5771",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5738",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5774",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8825",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8820",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8846",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10421",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5650",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5556",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8823",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5819",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5829",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5542",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8867",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5604",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5655",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10425",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5568",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5654",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5806",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5753",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8341",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9850",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5710",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10422",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5720",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10654",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5837",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5835",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5541",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9851",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8824",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8818",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5653",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5701",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5543",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5760",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5683",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=7169",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10682",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10467",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9704",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8806",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9710",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8805",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8813",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10464",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5578",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8784",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5674",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5785",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5796",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5783",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5786",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5798",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5790",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5606",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5700",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9849",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5702",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5820",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5570",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5772",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5678",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8329",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5658",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9847",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5832",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5817",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8808",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5666",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5615",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10462",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5591",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5717",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5756",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8817",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8804",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10466",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8862",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8448",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10650",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5550",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5706",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5708",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5863",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8334",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8802",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8809",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5586",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5784",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5787",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5795",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5791",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5782",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5746",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5625",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8899",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5748",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8816",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5773",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5684",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5729",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5575",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5614",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5671",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8843",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5619",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8865",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5652",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5610",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10677",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8801",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8324",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5766",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5608",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5808",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5664",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5757",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5662",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8811",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9724",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5823",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10649",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5831",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5761",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9720",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5544",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8445",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8803",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9716",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10465",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5818",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10419",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5807",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5558",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5809",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10408",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5826",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5670",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8447",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10694",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5810",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5811",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5812",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=11698",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5813",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5814",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5695",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5691",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5815",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9722",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5627",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10657",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5569",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5816",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5776",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5713",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5707",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9682",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5602",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8444",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9674",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5743",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10482",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5660",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5562",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5721",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5697",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5545",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5553",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5651",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5851",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5573",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5751",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5803",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5730",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5804",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5594",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5745",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5669",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9846",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5849",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=7167",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5750",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10409",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5563",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5661",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5677",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5638",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5599",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8333",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5632",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5752",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5841",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5548",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8828",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8895",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5759",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=10423",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8819",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5838",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8883",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5834",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5659",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5866",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5681",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5728",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=8810",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5554",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5780",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5574",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9684",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5688",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5788",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3040",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3159",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3098",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3042",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3044",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3099",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3066",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3161",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3231",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3163",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3102",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3164",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3128",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3103",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3166",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3191",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3067",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3167",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3069",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3130",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3168",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3104",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3070",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3071",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3131",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3133",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3134",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3221",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3169",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3193",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3194",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3105",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3072",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3073",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3075",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3045",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3107",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3109",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3136",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3137",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3139",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3140",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3142",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3171",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3174",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3175",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3046",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3144",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3232",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3047",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3195",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3078",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3196",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3197",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3145",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3079",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3199",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3200",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3233",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3202",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3080",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3081",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3234",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3111",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3112",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3083",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3222",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3223",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3048",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3224",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3203",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3225",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3049",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3084",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3050",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3226",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3146",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3147",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3205",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3177",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3086",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3113",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3227",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3088",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3051",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3052",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3053",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3178",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3179",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3180",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3208",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3209",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3089",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3181",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3211",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3212",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3055",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3214",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3235",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3215",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3236",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3056",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3057",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3091",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3058",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3237",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3115",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3116",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3060",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3062",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3182",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3118",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3148",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3093",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3063",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3120",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3121",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3183",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3094",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3122",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3228",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3216",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3096",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3217",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3150",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3238",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3123",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3124",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3151",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3153",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3218",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3064",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3185",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3187",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3189",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3125",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3127",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3229",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3155",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3065",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3219",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3230",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3156",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3158",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=992",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1064",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1065",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1050",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1051",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=993",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1057",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1036",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1066",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=994",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=995",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=996",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1058",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=997",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=998",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=999",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1067",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1052",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1000",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1001",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1002",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1003",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1053",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1004",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1068",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1059",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1037",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1005",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1060",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1038",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1006",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1054",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1039",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1061",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1007",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1008",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1040",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1041",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1009",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1010",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1069",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1011",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1012",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1071",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1013",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1075",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1014",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1015",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1062",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1016",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1042",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1043",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1055",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1044",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1017",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1018",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1045",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1070",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1019",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1046",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1020",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1063",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1021",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1076",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1022",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1023",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1024",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1025",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1026",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1027",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1028",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1056",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1047",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1029",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1030",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1031",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1080",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1032",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1084",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1091",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1033",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1034",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1048",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1049",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1035",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=968",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=955",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=900",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=901",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=956",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=957",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=970",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=984",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=959",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=902",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=903",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=971",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=904",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=985",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=914",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=942",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=905",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=929",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=986",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=960",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=943",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=987",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=944",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=906",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=988",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=915",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=916",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=945",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=972",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=930",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=907",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=932",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=946",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=933",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=918",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=919",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=961",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=947",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=935",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=989",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=908",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=909",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=910",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=973",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=921",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=922",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=923",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=974",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=962",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=990",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=963",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=936",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=948",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=964",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=976",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=983",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=950",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=991",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=937",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=925",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=978",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=911",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=979",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=912",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=965",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=913",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=951",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=938",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=939",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=980",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=940",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=952",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=926",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=928",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=941",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=981",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=954",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=967",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220525",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220454",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220517",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220498",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220553",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220539",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220562",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220540",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220487",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220488",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220573",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220482",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220518",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220556",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220455",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220499",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220476",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220451",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220513",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220519",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220567",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220548",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220473",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220456",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220477",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220474",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220554",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220457",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220526",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220520",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220534",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220507",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220684",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220452",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220489",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220521",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220475",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220478",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220500",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220458",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220479",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221295",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220583",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220483",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220495",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220585",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220467",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220504",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220584",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220468",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220501",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220563",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220464",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220546",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220508",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220469",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220459",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221301",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220484",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220557",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220490",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220470",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220535",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220465",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220491",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220544",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220568",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220527",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220528",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220496",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220536",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220509",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220569",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220529",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220510",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220532",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220460",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220522",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220485",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220570",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221305",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220545",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220461",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220586",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220523",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220511",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221309",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220514",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220571",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220541",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220542",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220543",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220577",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220576",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220515",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220471",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220582",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220462",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220505",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220588",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220492",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220561",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220549",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220587",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220572",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220480",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220493",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220466",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220537",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=222702",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220555",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220497",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220530",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220533",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221312",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220538",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220531",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220453",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220524",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220481",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220558",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220506",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220581",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220547",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220494",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220564",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220472",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220552",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220574",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220559",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220578",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220565",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220550",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220512",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220566",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220502",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220551",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220575",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220560",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220579",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220580",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430540",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430541",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430542",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430570",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430578",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430619",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430579",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430580",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430620",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430581",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430582",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430583",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430562",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430584",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430621",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430631",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430601",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430571",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430572",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430543",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430632",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430622",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430633",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430585",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430544",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430545",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430602",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430623",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430546",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430603",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430547",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430586",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430587",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430548",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430640",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430604",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430549",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430550",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430588",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430551",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430552",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430589",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430634",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430590",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430591",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430573",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430605",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430563",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430592",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430564",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430637",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430606",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430593",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430553",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430554",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430555",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430639",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430624",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430574",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430607",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430627",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430594",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430556",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430608",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430575",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430636",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430557",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430609",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430565",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430610",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430566",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430576",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430558",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430611",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430612",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430595",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430559",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430596",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430625",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430635",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430626",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430567",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430597",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430598",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430560",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430638",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430628",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430613",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430629",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430630",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430614",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430599",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430615",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430577",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430616",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430617",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430568",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430600",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430569",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430618",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430561",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401803",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401804",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401805",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401806",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401807",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401808",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401809",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401810",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401811",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401812",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401813",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401814",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401815",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401816",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401817",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401818",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401819",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401820",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401821",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401822",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401823",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401824",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401825",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401826",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401827",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401828",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401829",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401830",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401831",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401832",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401833",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401834",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401835",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401836",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401837",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401838",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401839",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401840",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401841",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401842",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401843",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401844",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401845",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401846",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401847",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401848",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401849",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401850",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401851",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401852",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401853",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401854",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401855",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401856",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401857",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401858",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401859",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401860",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401861",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401862",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401863",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401864",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401865",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401866",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401867",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401868",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401869",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401870",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401871",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401872",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401873",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401874",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401875",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401876",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401877",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401878",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401879",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401880",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401881",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401885",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401892",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401893",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401894",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401895",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401896",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401897",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401898",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401899",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401900",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401901",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401902",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401903",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401904",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401905",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401906",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401907",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401908",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401909",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401910",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401911",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401912",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401913",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401914",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401915",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401916",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401917",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401921",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401928",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401929",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401930",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401931",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401932",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401933",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401934",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401935",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401936",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401937",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401938",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401939",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401940",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401941",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401942",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401943",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401944",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401945",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401946",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401947",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401948",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401949",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401950",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401951",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401952",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401956",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401963",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401964",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401965",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401966",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401967",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401968",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401969",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401970",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401971",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401972",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401973",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401974",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401975",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401976",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401977",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401978",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401979",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401980",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401981",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401982",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401983",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401984",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401988",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401995",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401996",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401997",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401998",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401999",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402000",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402001",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402002",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402003",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402004",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402005",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402006",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402007",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402008",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402009",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402010",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402011",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402012",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402014",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402013",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402015",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402016",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402017",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402018",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402019",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402020",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402021",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402022",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402023",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402024",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402025",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402026",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402027",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402028",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402029",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402030",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402031",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402032",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402033",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402034",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402035",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402036",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402037",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402038",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402039",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402040",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402041",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402042",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402043",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402044",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402045",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402046",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402047",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402048",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402049",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402050",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402051",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402052",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402056",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402063",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402064",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402065",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402066",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402067",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402068",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402069",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402070",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402071",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402072",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402073",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402074",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402075",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402076",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402077",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402078",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402079",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402080",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402081",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402082",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402083",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402084",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402085",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402086",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402087",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402088",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402089",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402090",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402091",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402092",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402093",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402094",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402095",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402096",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402097",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402098",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402099",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402100",
    # "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=402101"
  ]
end
